Dados a serem buscados: 
[Raça, Ocupação, Grau de instrução, Gênero, Declaração de bens, Eleito?]

In [24]:
import os
import pandas as pd

In [25]:
df_candidatos_2020 = pd.read_csv('/home/mariana/Downloads/consulta_cand_2020_RN.csv', sep=';', error_bad_lines=False, encoding='iso-8859-1')

In [26]:
df_candidatos_2020 = df_candidatos_2020[['DS_GENERO', 'DS_OCUPACAO', 'DS_COR_RACA', 'DS_GRAU_INSTRUCAO', 'ST_DECLARAR_BENS', 'SQ_CANDIDATO', 'DT_NASCIMENTO']]

In [27]:
df_eleicoes_rn_2020 = pd.read_csv('/home/mariana/Downloads/votacao_candidato_munzona_2020_RN.csv', sep=';', error_bad_lines=False, encoding='iso-8859-1')

In [28]:
df_eleicoes_rn_2020 = df_eleicoes_rn_2020[['SQ_CANDIDATO', 'DS_SIT_TOT_TURNO', 'QT_VOTOS_NOMINAIS']]

In [73]:
df_receitas = pd.read_csv('/home/mariana/Downloads/receitas_candidatos_2020_RN.csv', sep=';', encoding='iso-8859-1')

In [74]:
df_despesas = pd.read_csv('/home/mariana/Downloads/despesas_contratadas_candidatos_2020_RN.csv', sep=';', encoding='iso-8859-1')

In [77]:
df_receitas = df_receitas[['SQ_CANDIDATO', 'VR_RECEITA', 'DS_CARGO']]
df_despesas = df_despesas[['SQ_CANDIDATO', 'VR_DESPESA_CONTRATADA', 'DS_CARGO']]

In [79]:
df_despesas

       SQ_CANDIDATO VR_DESPESA_CONTRATADA  DS_CARGO
0      200000673078                 10,00  Vereador
1      200000668312                 10,45  Vereador
2      200000867579                  1,20  Prefeito
3      200000777272                  6,45  Vereador
4      200000801500                 47,01  Prefeito
...             ...                   ...       ...
81740  200000765172                300,00  Vereador
81741  200000765178                 66,00  Vereador
81742  200000765178                130,00  Vereador
81743  200000765178                 35,00  Vereador
81744  200000765178                160,00  Vereador

[81745 rows x 3 columns]

In [29]:
df_dados_cand = df_candidatos_2020.merge(df_eleicoes_rn_2020, how='inner', on='SQ_CANDIDATO')

In [48]:
df_mulheres = df_dados_cand[df_dados_cand['DS_GENERO'] == 'FEMININO']

In [65]:
#pd.to_numeric(df_mulheres['QT_VOTOS_NOMINAIS'])
df_naosuplentes = df_mulheres[df_mulheres['DS_SIT_TOT_TURNO']!='SUPLENTE']
df_naosuplentes[df_naosuplentes['DS_SIT_TOT_TURNO']!='NÃO ELEITO']

,DS_GENERO,DS_OCUPACAO,DS_COR_RACA,DS_GRAU_INSTRUCAO,ST_DECLARAR_BENS,SQ_CANDIDATO,DT_NASCIMENTO,DS_SIT_TOT_TURNO,QT_VOTOS_NOMINAIS
74,FEMININO,PEDAGOGO,BRANCA,SUPERIOR COMPLETO,S,200001027258,12/12/1969,ELEITO POR QP,281
96,FEMININO,TÉCNICO DE ENFERMAGEM E ASSEMELHADOS (EXCETO E...,BRANCA,ENSINO MÉDIO COMPLETO,S,200000769004,05/06/1980,ELEITO,2762
98,FEMININO,DONA DE CASA,PRETA,ENSINO MÉDIO COMPLETO,S,200001228051,28/09/1983,ELEITO POR QP,599
207,FEMININO,ASSISTENTE SOCIAL,BRANCA,SUPERIOR COMPLETO,S,200001137727,15/11/1985,ELEITO POR QP,647
214,FEMININO,VEREADOR,BRANCA,SUPERIOR INCOMPLETO,S,200000853918,27/09/1968,ELEITO POR QP,752
...,...,...,...,...,...,...,...,...,...
8938,FEMININO,VEREADOR,BRANCA,SUPERIOR COMPLETO,S,200001041656,09/10/1977,ELEITO POR QP,810
8984,FEMININO,PROFESSOR DE ENSINO FUNDAMENTAL,PARDA,SUPERIOR COMPLETO,S,200000914769,26/04/1988,ELEITO POR QP,176
8986,FEMININO,VEREADOR,PARDA,ENSINO MÉDIO COMPLETO,S,200000980649,25/09/1983,ELEITO POR QP,372
8993,FEMININO,PREFEITO,PARDA,ENSINO MÉDIO COMPLETO,N,200000991531,07/05/1962,ELEITO,4134
8995,FEMININO,VEREADOR,BRANCA,SUPERIOR COMPLETO,S,200000952121,27/02/1968,ELEITO POR MÉDIA,575

In [83]:
df_dados_cand['DS_GENERO'].value_counts()

MASCULINO    5908
FEMININO     3100
Name: DS_GENERO, dtype: int64

In [33]:
df_dados_cand

,DS_GENERO,DS_OCUPACAO,DS_COR_RACA,DS_GRAU_INSTRUCAO,ST_DECLARAR_BENS,SQ_CANDIDATO,DT_NASCIMENTO,DS_SIT_TOT_TURNO,QT_VOTOS_NOMINAIS
0,MASCULINO,SERVIDOR PÚBLICO MUNICIPAL,PARDA,SUPERIOR COMPLETO,S,200000719888,28/11/1969,SUPLENTE,46
1,MASCULINO,SERVIDOR PÚBLICO MUNICIPAL,PRETA,ENSINO MÉDIO COMPLETO,S,200000884351,30/12/1956,SUPLENTE,28
2,MASCULINO,OUTROS,PARDA,ENSINO MÉDIO INCOMPLETO,S,200001084311,09/04/1991,NÃO ELEITO,116
3,MASCULINO,OUTROS,BRANCA,ENSINO MÉDIO COMPLETO,S,200001052838,28/10/1965,SUPLENTE,858
4,FEMININO,AGRICULTOR,PRETA,ENSINO MÉDIO COMPLETO,S,200000843676,24/05/1983,SUPLENTE,5
...,...,...,...,...,...,...,...,...,...
9003,MASCULINO,ODONTÓLOGO,PARDA,SUPERIOR COMPLETO,S,200001002497,29/11/1984,ELEITO POR QP,790
9004,MASCULINO,VEREADOR,PARDA,ENSINO MÉDIO COMPLETO,S,200000655294,23/08/1982,SUPLENTE,232
9005,MASCULINO,"ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS",BRANCA,SUPERIOR INCOMPLETO,S,200000783988,31/07/2001,NÃO ELEITO,27
9006,MASCULINO,AGRICULTOR,BRANCA,ENSINO FUNDAMENTAL INCOMPLETO,S,200000886513,26/04/1977,SUPLENTE,107
9007,MASCULINO,ADMINISTRADOR,PARDA,SUPERIOR COMPLETO,S,200001143953,19/07/1981,NÃO ELEITO,76

In [87]:
dados_nao_supervisionados = df_dados_cand[['DS_GENERO','DS_OCUPACAO','DS_COR_RACA','DS_GRAU_INSTRUCAO','ST_DECLARAR_BENS', "DS_SIT_TOT_TURNO"]]

In [88]:
dados_nao_supervisionados.to_excel('dados nao supervisionados.xlsx')